version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/gradleupdate
    steps:
      - checkout
      - run: ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: ~/gradleupdate
    steps:
      - run: apk --update add openjdk8
      - run: gcloud components install app-engine-java
      - checkout
      - attach_workspace:
          at: .
      - run: echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > "$HOME/gcp-service-account-key.json"
      - run: gcloud auth activate-service-account --key-file "$HOME/gcp-service-account-key.json"
      - run: echo "$DOTENV" | base64 -d > .env
      - run: ./gradlew appengineDeploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
