logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hidetake.gradleupdate: DEBUG

spring:
  main:
    banner-mode: "off"

github:
  oauth:
    redirect-url: https://github.com/login/oauth/authorize
    scope: public_repo
