logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hidetake.gradleupdate: DEBUG

spring:
  main:
    banner-mode: "off"

github:
  oauth:
    client-id: ${github.client.id}
    client-secret: ${github.client.secret}
    scope: public_repo
